force-app/main/default/objects/Company_Agency_Match__c/Company_Agency_Match__c.object-meta.xml
<CustomObject>
    <description>Pair up a company with an Agency Project (Site Visit) and use this pairing to add any further required info to generate the HOC objects &quot;Volunteer Opportunity&quot; and one &quot;Occurrence&quot;.  This can be saved as a draft until a &quot;Generate on Save&quot; checkbox is checked.  The checkbox will generate a Volunteer Opportunity unless if finds one already for this combination.  To regenerate delete the existing one.</description>
    <label>Company Agency Match</label>
    <nameField>
        <displayFormat>match{0000}</displayFormat>
        <label>Company Agency Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Agency Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Agency_Match__c/fields/Company_Intake__c.field-meta.xml
<CustomField>
    <fullName>Company_Intake__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company Intake</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Company_Intake__c.Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Company__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Company_Intake__c</referenceTo>
    <relationshipLabel>Company Agency Matches</relationshipLabel>
    <relationshipName>Company_Agency_Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Agency_Match__c/fields/Generate_on_Save__c.field-meta.xml
<CustomField>
    <fullName>Generate_on_Save__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box after all data is entered for the Volunteer Opportunity.  If you want to re-generate the Volunteer Opportunity from changed data then delete the existing Volunteer Opportunity first.</inlineHelpText>
    <label>Generate on Save</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Company_Agency_Match__c/fields/Min_Volunteer_Age_w_adult__c.field-meta.xml
<CustomField>
    <fullName>Min_Volunteer_Age_w_adult__c</fullName>
    <formula>Project_Site_Visit__r.Min_Volunteer_Age_w_adult__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Volunteer Age (w/adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Company_Agency_Match__c/fields/Minimum_Volunteer_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Volunteer_Age__c</fullName>
    <formula>Project_Site_Visit__r.Minimum_Volunteer_Age__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minimum Volunteer Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Company_Agency_Match__c/fields/Project_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Date__c</fullName>
    <formula>Project_Site_Visit__r.Project_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Company_Agency_Match__c/fields/Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_End_Date__c</fullName>
    <formula>Project_Site_Visit__r.Project_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Company_Agency_Match__c/fields/Project_Location__c.field-meta.xml
<CustomField>
    <fullName>Project_Location__c</fullName>
    <formula>Project_Site_Visit__r.Project_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Agency_Match__c/fields/Project_Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Project_Site_Visit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is the project to which this match is connected.</inlineHelpText>
    <label>Project Site Visit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project_Site_Visit__c.Nonprofit_Agency__c</field>
            <operation>equals</operation>
            <valueField>$Source.Agency__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Project_Site_Visit__c</referenceTo>
    <relationshipLabel>Company Agency Matches</relationshipLabel>
    <relationshipName>Company_Agency_Matches</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Intake__c/Company_Intake__c.object-meta.xml
<CustomObject>
    <description>Set of questions pertaining to a particular desired volunteer event at this company.</description>
    <label>Company Intake</label>
    <nameField>
        <displayFormat>intake{000000}</displayFormat>
        <label>Company Intake Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Intakes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Intake__c/fields/Project_Location__c.field-meta.xml
<CustomField>
    <fullName>Project_Location__c</fullName>
    <inlineHelpText>Preferences about Project Location</inlineHelpText>
    <label>Project Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/Project_Site_Visit__c.object-meta.xml
<CustomObject>
    <description>Information recorded during an agency site visit for a particular project.  Used for the corporate projects (not the calendar projects, see &quot;Calendar Intake&quot; for that).</description>
    <label>Project Site Visit</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Site_Visit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This description of the project will be used in the Volunteer Opportunity.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Local_Impact_Area__c.field-meta.xml
<CustomField>
    <fullName>Local_Impact_Area__c</fullName>
    <inlineHelpText>used to populate Volunteer Opportunity field &quot;Impact Area (Local)&quot;.</inlineHelpText>
    <label>Local Impact Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Basic Needs</fullName>
            </value>
            <value>
                <fullName>Emergency Preparedness/DART</fullName>
            </value>
            <value>
                <fullName>Ensuring Young People Succeed</fullName>
            </value>
            <value>
                <fullName>Equipping Adults to Beat Poverty</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>New Volunteer or Project Leader Training</fullName>
            </value>
            <value>
                <fullName>Boston Cares Programming &amp; Support</fullName>
            </value>
            <value>
                <fullName>Cultural &amp; Environmental Vibrancy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Min_Volunteer_Age_w_adult__c.field-meta.xml
<CustomField>
    <fullName>Min_Volunteer_Age_w_adult__c</fullName>
    <label>Min Volunteer Age (w/adult)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Minimum_Volunteer_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Volunteer_Age__c</fullName>
    <label>Minimum Volunteer Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Primary_Impact_Area__c.field-meta.xml
<CustomField>
    <fullName>Primary_Impact_Area__c</fullName>
    <inlineHelpText>used by Volunteer Opportunity, required.</inlineHelpText>
    <label>Primary Impact Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adult Education</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Arts &amp; Culture</fullName>
            </value>
            <value>
                <fullName>Children &amp; Youth Education</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Disaster &amp; Emergency Services</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Faith-Based Service</fullName>
            </value>
            <value>
                <fullName>Family Services</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Hunger &amp; Homelessness</fullName>
            </value>
            <value>
                <fullName>Immigrant &amp; Refugee Services</fullName>
            </value>
            <value>
                <fullName>International Service</fullName>
            </value>
            <value>
                <fullName>Internships &amp; Employment</fullName>
            </value>
            <value>
                <fullName>Justice &amp; Legal Services</fullName>
            </value>
            <value>
                <fullName>Schools</fullName>
            </value>
            <value>
                <fullName>Senior Services</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Recreation</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Project_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Date__c</fullName>
    <inlineHelpText>Planned upon date for the project to occur</inlineHelpText>
    <label>Project Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_End_Date__c</fullName>
    <inlineHelpText>Provide a value if this is a mutl-day project.</inlineHelpText>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Project_Location__c.field-meta.xml
<CustomField>
    <fullName>Project_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Required to generate the Volunteer Opportunity.</inlineHelpText>
    <label>Project Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>HOC__Location__c.HOC__Organization__c</field>
            <operation>equals</operation>
            <valueField>$Source.Nonprofit_Agency__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>HOC__Location__c</referenceTo>
    <relationshipLabel>Project Site Visits</relationshipLabel>
    <relationshipName>Project_Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Secondary_Impact_Area__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Impact_Area__c</fullName>
    <inlineHelpText>used by Volunteer Opportunity, optional</inlineHelpText>
    <label>Secondary Impact Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adult Education</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Arts &amp; Culture</fullName>
            </value>
            <value>
                <fullName>Children &amp; Youth Education</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Disaster &amp; Emergency Services</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Faith-Based Service</fullName>
            </value>
            <value>
                <fullName>Family Services</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Hunger &amp; Homelessness</fullName>
            </value>
            <value>
                <fullName>Immigrant &amp; Refugee Services</fullName>
            </value>
            <value>
                <fullName>International Service</fullName>
            </value>
            <value>
                <fullName>Internships &amp; Employment</fullName>
            </value>
            <value>
                <fullName>Justice &amp; Legal Services</fullName>
            </value>
            <value>
                <fullName>Schools</fullName>
            </value>
            <value>
                <fullName>Senior Services</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Recreation</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/TestCompAgencyMatchInsert.cls
@IsTest(SeeAllData=true) public class TestCompAgencyMatchInsert
{
    // because we could not create a Location object try this approach
    // using existing data instead of creating from scratch.
    // already wrote most of it just try using an existing location,
    // actually that won't work as the ids will require consistently
    // using existing data.
    static testMethod void testGenTriggers3()
    {
        List<Account> company = [select Id,Name from Account where Name = 'EMC'];
        System.assertEquals (company.size(), 1, 'EMC not found.');
        List<Company_Intake__c> ci = [select Id from Company_Intake__c where Name = 'intake000000'];
        System.assertEquals (ci.size(), 1, 'company intake 1 not found');
        List<Account> agency = [Select Name,HOC__Impact_Area__c,
            HOC__Genders_Served__c,HOC__Age_Groups_Served__c
            from Account where Name = 'Massachusetts Audubon Society - Drumlin Farms'];
        System.assertEquals (agency.size(), 1, 'Drumlin Account not found.');
        List<HOC__Location__c> locList = [Select Id from HOC__Location__c where Name = 'Drumlin Farm, Nature Center'];
        System.assertEquals (locList.size(), 1, 'Drumlin location not found.');
        List<Project_Site_Visit__c> projsv =
            [Select Name,Project_Date__c,Project_End_Date__c,
             Minimum_Volunteer_Age__c,Min_Volunteer_Age_w_adult__c,
             Project_Location__c,Description__c,
             Primary_Impact_Area__c,Secondary_Impact_Area__c,Local_Impact_Area__c
             from Project_Site_Visit__c where Name = 'Drumlin Farms Site Visit'];
        System.assertEquals (projsv.size(), 1, 'Drumlin Proj not found.');

        // insert a minimal company agency match
        Company_Agency_Match__c cam = new Company_Agency_Match__c();
        cam.Company_Intake__c = ci.get(0).Id;
        cam.Project_Site_Visit__c = projsv.get(0).Id;
        cam.Generate_on_Save__c = true;
        insert cam;
    }
}