force-app/main/default/objects/Project_Site_Visit__c/Project_Site_Visit__c.object-meta.xml
<CustomObject>
    <description>Information recorded during an agency site visit for a particular project.  Used for the corporate projects (not the calendar projects, see &quot;Calendar Intake&quot; for that).</description>
    <label>Project Site Visit</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Site_Visit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This description of the project will be used in the Volunteer Opportunity.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Min_Volunteer_Age_w_adult__c.field-meta.xml
<CustomField>
    <fullName>Min_Volunteer_Age_w_adult__c</fullName>
    <label>Min Volunteer Age (w/adult)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Minimum_Volunteer_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Volunteer_Age__c</fullName>
    <label>Minimum Volunteer Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Nonprofit_Agency__c.field-meta.xml
<CustomField>
    <fullName>Nonprofit_Agency__c</fullName>
    <description>This will be pre-filled when launched from that Organization&apos;s page</description>
    <label>Nonprofit Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Site_Visit_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Project_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Date__c</fullName>
    <inlineHelpText>Planned upon date for the project to occur</inlineHelpText>
    <label>Project Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Contingency_Plan__c.field-meta.xml
<CustomField>
    <fullName>Contingency_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>In the case of inclement weather, indoor tasks that could substitute for cancelled outdoor tasks.</inlineHelpText>
    <label>Contingency Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project_Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Project_Site_Visit__c</fullName>
    <label>Project Site Visit</label>
    <referenceTo>Project_Site_Visit__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <inlineHelpText>Tasks should be numbered separately for contingency plan tasks.</inlineHelpText>
    <label>Task Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/TestProjTask.cls
@IsTest public class TestProjTask
{
    static testMethod void testDupId()
    {
        RecordType rectype = [select Id from RecordType where Name = 'Nonprofit'];
        Account agency = new Account();
        agency.RecordTypeId = rectype.Id;
        agency.Name = 'Pine St Inn';
        agency.HOC__Genders_Served__c = 'Female';
        agency.HOC__Impact_Area__c = 'Hunger & Homelessness';
        agency.HOC__Age_Groups_Served__c = 'All ages';
        insert agency;
        List<Account> agencyList = [select Id from Account where Name = 'Pine St Inn'];
        System.assertEquals (agencyList.size(), 1, 'Pine St Inn insert failed.');
        // proj
        Project_Site_Visit__c psv = new Project_Site_Visit__c();
        psv.Name = 'Serve Dinner';
        Date projDate = Date.newInstance (2015, 3, 16);
        psv.Project_Date__c = projDate;
        psv.Nonprofit_Agency__c = agencyList.get(0).Id;
        psv.Minimum_Volunteer_Age__c = 18;
        psv.Min_Volunteer_Age_w_adult__c = 17;
        psv.Description__c = 'a cool project';
        insert psv;
        List<Project_Site_Visit__c> psvList = [select Id from Project_Site_Visit__c where Name = 'Serve Dinner'];
        System.assertEquals (psvList.size(), 1, 'Serve Dinner insert failed.');
        // task
        Project_Task__c task = new Project_Task__c();
        task.Task_Number__c = 1;
        task.Name = 'Fill Dumpster';
        task.Project_Site_Visit__c = psvList.get(0).Id;
        insert task;
        // test 1 insert same numbered task in same project
        task = new Project_Task__c();
        task.Task_Number__c = 1;
        task.Name = 'Empty Dumpster';
        task.Project_Site_Visit__c = psvList.get(0).Id;
        try
        {
            insert task;
        }
        catch (Exception e)
        {
            system.debug (Logginglevel.INFO, e.getMessage());
            system.assert (e.getMessage().contains('Another task'));
        }
        // test 2 apply the contingency flag making it a diff task
        task = new Project_Task__c();
        task.Task_Number__c = 1;
        task.Contingency_Plan__c = true;
        task.Name = 'Wash Floors';
        task.Project_Site_Visit__c = psvList.get(0).Id;
        insert task;
        // test 3 apply the same task to diff proj
        // proj 2
        Project_Site_Visit__c psv2 = new Project_Site_Visit__c();
        psv2.Name = 'Serve Lunch';
        psv2.Project_Date__c = projDate;
        psv2.Nonprofit_Agency__c = agencyList.get(0).Id;
        insert psv2;
        // try retrieve without list
        Project_Site_Visit__c psv2Single = [select Id from Project_Site_Visit__c where Name = 'Serve Lunch'];
        System.assertNotEquals (psv2Single, null, 'Serve Lunch insert failed.');
        task = new Project_Task__c();
        task.Task_Number__c = 1;
        //task.Contingency_Plan__c = false;
        task.Name = 'Make Doughnuts';
        task.Project_Site_Visit__c = psv2Single.Id;
        insert task;
    }
}