force-app/main/default/objects/Account/fields/Walk_in_or_Appointment_Only__c.field-meta.xml
<CustomField>
    <fullName>Walk_in_or_Appointment_Only__c</fullName>
    <label>Appointment Only or Walk-in?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appointment Only</fullName>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/Project_Site_Visit__c.object-meta.xml
<CustomObject>
    <description>Information recorded during an agency site visit for a particular project.  Used for the corporate projects (not the calendar projects, see &quot;Calendar Intake&quot; for that).</description>
    <label>Project Site Visit</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Site_Visit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This description of the project will be used in the Volunteer Opportunity.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Local_Impact_Area__c.field-meta.xml
<CustomField>
    <fullName>Local_Impact_Area__c</fullName>
    <inlineHelpText>used to populate Volunteer Opportunity field &quot;Impact Area (Local)&quot;.</inlineHelpText>
    <label>Local Impact Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Basic Needs</fullName>
            </value>
            <value>
                <fullName>Emergency Preparedness/DART</fullName>
            </value>
            <value>
                <fullName>Ensuring Young People Succeed</fullName>
            </value>
            <value>
                <fullName>Equipping Adults to Beat Poverty</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>New Volunteer or Project Leader Training</fullName>
            </value>
            <value>
                <fullName>Boston Cares Programming &amp; Support</fullName>
            </value>
            <value>
                <fullName>Cultural &amp; Environmental Vibrancy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Min_Volunteer_Age_w_adult__c.field-meta.xml
<CustomField>
    <fullName>Min_Volunteer_Age_w_adult__c</fullName>
    <label>Min Volunteer Age (w/adult)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Minimum_Volunteer_Age__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Volunteer_Age__c</fullName>
    <label>Minimum Volunteer Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Nonprofit_Agency__c.field-meta.xml
<CustomField>
    <fullName>Nonprofit_Agency__c</fullName>
    <description>This will be pre-filled when launched from that Organization&apos;s page</description>
    <label>Nonprofit Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Site_Visit_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Primary_Impact_Area__c.field-meta.xml
<CustomField>
    <fullName>Primary_Impact_Area__c</fullName>
    <inlineHelpText>used by Volunteer Opportunity, required.</inlineHelpText>
    <label>Primary Impact Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adult Education</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Arts &amp; Culture</fullName>
            </value>
            <value>
                <fullName>Children &amp; Youth Education</fullName>
            </value>
            <value>
                <fullName>Civic &amp; Community</fullName>
            </value>
            <value>
                <fullName>Disaster &amp; Emergency Services</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Faith-Based Service</fullName>
            </value>
            <value>
                <fullName>Family Services</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Hunger &amp; Homelessness</fullName>
            </value>
            <value>
                <fullName>Immigrant &amp; Refugee Services</fullName>
            </value>
            <value>
                <fullName>International Service</fullName>
            </value>
            <value>
                <fullName>Internships &amp; Employment</fullName>
            </value>
            <value>
                <fullName>Justice &amp; Legal Services</fullName>
            </value>
            <value>
                <fullName>Schools</fullName>
            </value>
            <value>
                <fullName>Senior Services</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Recreation</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Project_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Date__c</fullName>
    <inlineHelpText>Planned upon date for the project to occur</inlineHelpText>
    <label>Project Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Project_Location__c.field-meta.xml
<CustomField>
    <fullName>Project_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Required to generate the Volunteer Opportunity.</inlineHelpText>
    <label>Project Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>HOC__Location__c.HOC__Organization__c</field>
            <operation>equals</operation>
            <valueField>$Source.Nonprofit_Agency__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>HOC__Location__c</referenceTo>
    <relationshipLabel>Project Site Visits</relationshipLabel>
    <relationshipName>Project_Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Site_Visit__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>12:30 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>1:30 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>2:30 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>3:30 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>4:30 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>5:30 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>6:30 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>7:30 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>8:30 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>9:30 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:30 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:30 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Contingency_Plan__c.field-meta.xml
<CustomField>
    <fullName>Contingency_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>In the case of inclement weather, indoor tasks that could substitute for cancelled outdoor tasks.</inlineHelpText>
    <label>Contingency Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project_Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Project_Site_Visit__c</fullName>
    <label>Project Site Visit</label>
    <referenceTo>Project_Site_Visit__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <inlineHelpText>Tasks should be numbered separately for contingency plan tasks.</inlineHelpText>
    <label>Task Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestProjTask.cls
@IsTest public class TestProjTask
{
  public static ID nonprofit = schema.SObjectType.Account.getRecordTypeInfosByName().get('Nonprofit').getRecordTypeId();

    static testMethod void testDupId()
    {
        Account agency = new Account();
        agency.RecordTypeId = nonprofit;
        agency.Name = 'Pine St Inn';
        agency.Walk_in_or_Appointment_Only__c = 'Walk-in';
        agency.HOC__Primary_Address__c = 'Shipping';
        agency.HOC__Address_Visibility__c = 'City and Zip only';
        agency.HOC__Status__c = 'Active Partner';
        agency.HOC__Genders_Served__c = 'Female';
        agency.HOC__Impact_Area__c = 'Hunger & Homelessness';
        agency.HOC__Age_Groups_Served__c = 'All ages';
        agency.ShippingStreet = '123 Fake Street';
  			agency.ShippingCity = 'Fake City';
  			agency.ShippingState = 'MA';
  			agency.ShippingPostalCode = '02446';
  			agency.ShippingCountry = 'USA';

        try{
            insert agency;
        } catch (Exception e){
            System.debug(e);
        }

        // List<Account> agencyList = [select Id from Account where Name = 'Pine St Inn'];
        // System.assertEquals (agencyList.size(), 1, 'Pine St Inn insert failed.');

        // Create a Zip Code
    		HOC__ZipCode__c zipCodeRecord = new HOC__ZipCode__c();
    		zipCodeRecord.Name = '02446';
    		insert zipCodeRecord;

        // Create a Location
    		HOC__Location__c locationRecord = new HOC__Location__c();
    		locationRecord.Name = 'Test Location';
    		locationRecord.HOC__Street__c = 'Test Street';
    		locationRecord.HOC__City__c = 'Test City';
    		locationRecord.HOC__Zip_Postal_Code__c = zipCodeRecord.id;
    		locationRecord.HOC__Zip_Code__c = '02446';
    		locationRecord.HOC__Country__c = 'USA';
    		locationRecord.HOC__Organization__c = agency.id;
    		insert locationRecord;

        Project_Site_Visit__c projsv = new Project_Site_Visit__c();
        Date projDate = Date.newInstance (2015, 3, 16);
        projsv.Project_Date__c = projDate;
        projsv.Name = 'Serve Dinner';
        projsv.Nonprofit_Agency__c = agency.id;
        projsv.Primary_Impact_Area__c = 'Adult Education';
        projsv.Local_Impact_Area__c = 'Basic Needs';
        projsv.Project_Location__c = locationRecord.id;
        projsv.Min_Volunteer_Age_w_adult__c = 18;
        projsv.Minimum_Volunteer_Age__c = 18;
        projsv.Description__c = 'Test Description';
        projsv.Start_Time__c = '8:00 AM';
        projsv.End_Time__c = '9:00 AM';
        insert projsv;

        // List<Project_Site_Visit__c> psvList = [select Id from Project_Site_Visit__c where Name = 'Serve Dinner'];
        // System.assertEquals (psvList.size(), 1, 'Serve Dinner insert failed.');

        // task
        Project_Task__c task = new Project_Task__c();
        task.Task_Number__c = 1;
        task.Name = 'Fill Dumpster';
        task.Project_Site_Visit__c = projsv.Id;
        insert task;
        // test 1 insert same numbered task in same project
        task = new Project_Task__c();
        task.Task_Number__c = 1;
        task.Name = 'Empty Dumpster';
        task.Project_Site_Visit__c = projsv.Id;
        try
        {
            insert task;
        }
        catch (Exception e)
        {
            system.debug (Logginglevel.INFO, e.getMessage());
            system.assert (e.getMessage().contains('Another task'));
        }
        // test 2 apply the contingency flag making it a diff task
        task = new Project_Task__c();
        task.Task_Number__c = 1;
        task.Contingency_Plan__c = true;
        task.Name = 'Wash Floors';
        task.Project_Site_Visit__c = projsv.Id;
        insert task;
        // test 3 apply the same task to diff proj
        // proj 2
        Project_Site_Visit__c psv2 = new Project_Site_Visit__c();
        psv2.Name = 'Serve Lunch';
        psv2.Project_Date__c = projDate;
        psv2.Nonprofit_Agency__c = agency.Id;
        insert psv2;
        // try retrieve without list
        // Project_Site_Visit__c psv2Single = [select Id from Project_Site_Visit__c where Name = 'Serve Lunch'];
        // System.assertNotEquals (psv2Single, null, 'Serve Lunch insert failed.');
        task = new Project_Task__c();
        task.Task_Number__c = 1;
        //task.Contingency_Plan__c = false;
        task.Name = 'Make Doughnuts';
        task.Project_Site_Visit__c = psv2.Id;
        insert task;

    }
}