force-app/main/default/objects/Account/fields/Walk_in_or_Appointment_Only__c.field-meta.xml
<CustomField>
    <fullName>Walk_in_or_Appointment_Only__c</fullName>
    <label>Appointment Only or Walk-in?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appointment Only</fullName>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VL_Training_Completed__c.field-meta.xml
<CustomField>
    <fullName>VL_Training_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Did the volunteer complete a volunteer leader training?</description>
    <label>VL Training Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/HOC__Volunteer_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Apply_Restrictions_to_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>HOC__Apply_Restrictions_to_Opportunity__c</fullName>
    <label>Apply Restrictions to Opportunity</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HOC__Registration_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Apply Restrictions</fullName>
            </value>
            <value>
                <fullName>Do NOT Apply Restrictions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__City__c.field-meta.xml
<CustomField>
    <fullName>HOC__City__c</fullName>
    <formula>HOC__City_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Country__c.field-meta.xml
<CustomField>
    <fullName>HOC__Country__c</fullName>
    <formula>HOC__Country_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Default_Location__c.field-meta.xml
<CustomField>
    <fullName>HOC__Default_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Location</label>
    <referenceTo>HOC__Location__c</referenceTo>
    <relationshipLabel>Volunteer Opportunities</relationshipLabel>
    <relationshipName>Volunteer_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Disaster_Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>HOC__Disaster_Opportunity_Type__c</fullName>
    <label>Disaster Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Emergency Preparedness</fullName>
            </value>
            <value>
                <fullName>Disaster Response &amp; Recovery</fullName>
            </value>
            <value>
                <fullName>Not Disaster Related</fullName>
                <default>true</default>
                <label>Not Disaster Related</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__End_Date__c.field-meta.xml
<CustomField>
    <fullName>HOC__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Managed_By__c.field-meta.xml
<CustomField>
    <fullName>HOC__Managed_By__c</fullName>
    <inlineHelpText>Value once set cannot be changed</inlineHelpText>
    <label>Managed By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Maximum_Attendance__c.field-meta.xml
<CustomField>
    <fullName>HOC__Maximum_Attendance__c</fullName>
    <label>Maximum Attendance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Minimum_Age_w_adult__c.field-meta.xml
<CustomField>
    <fullName>HOC__Minimum_Age_w_adult__c</fullName>
    <label>Minimum Age (w/ adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Minimum_Age_w_o_adult__c.field-meta.xml
<CustomField>
    <fullName>HOC__Minimum_Age_w_o_adult__c</fullName>
    <label>Minimum Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Minimum_Attendance__c.field-meta.xml
<CustomField>
    <fullName>HOC__Minimum_Attendance__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Minimum Attendance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Opportunity_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>HOC__Opportunity_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a valid contact.</errorMessage>
        <filterItems>
            <field>Contact.HOC__Username__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <infoMessage>You can only assign contacts with the username field populated as Opportunity Coordinators.
If you do not see the contact you need in the search results, please contact the staff at the volunteer center to verify the contact record.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Opportunities</relationshipLabel>
    <relationshipName>Volunteer_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Organization_Served__c.field-meta.xml
<CustomField>
    <fullName>HOC__Organization_Served__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization Served</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.HOC__Status__c</field>
            <operation>equals</operation>
            <value>Active Partner</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>HOC Customer</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Employee Coordinator</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Account.CreatedById</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Volunteer Opportunities (Organization Served)</relationshipLabel>
    <relationshipName>Volunteer_Opportunity_Org_Served</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Orientation_Required__c.field-meta.xml
<CustomField>
    <fullName>HOC__Orientation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Orientation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Posting_Status__c.field-meta.xml
<CustomField>
    <fullName>HOC__Posting_Status__c</fullName>
    <description>Dependent on the Status field.</description>
    <label>Posting Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Registration_Deadline__c.field-meta.xml
<CustomField>
    <fullName>HOC__Registration_Deadline__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>The number of hours prior to the start time of the project to cut-off volunteer sign-up. (input a number) 
This number becomes the default value for all occurrences and can be changed at the occurrence level.</inlineHelpText>
    <label>Registration cutoff (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>HOC__Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HOC__Schedule_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Sign Up</fullName>
            </value>
            <value>
                <fullName>Express Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Schedule_Type__c.field-meta.xml
<CustomField>
    <fullName>HOC__Schedule_Type__c</fullName>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Date &amp; Time Specific</fullName>
            </value>
            <value>
                <fullName>Individually Scheduled</fullName>
            </value>
            <value>
                <fullName>To Be Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Skilled_Volunteer_Required__c.field-meta.xml
<CustomField>
    <fullName>HOC__Skilled_Volunteer_Required__c</fullName>
    <label>Skilled Volunteer Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>HOC__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Status__c.field-meta.xml
<CustomField>
    <fullName>HOC__Status__c</fullName>
    <inlineHelpText>Active - visible on website 
Pending - not yet visible publicly 
Awaiting Approval - submitted for approval by partner 
Admin - opportunities managed internally, not for public view 
Inactive – formally active, now retired from use on public site</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#E27001</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <color>#78C953</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <color>#0B6FCE</color>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#A845DC</color>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Street__c.field-meta.xml
<CustomField>
    <fullName>HOC__Street__c</fullName>
    <formula>HOC__Default_Location__r.HOC__Street__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Type__c.field-meta.xml
<CustomField>
    <fullName>HOC__Type__c</fullName>
    <inlineHelpText>Project - a volunteer opportunity that will result in service hours 
Activity - any other opportunity you wish to put on calendar, Activities will be further defined by the type of activity</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>HOC__Zip_Postal_Code__c</fullName>
    <formula>HOC__Default_Location__r.HOC__Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip/Postal Code</label>
    <type>Text</type>
</CustomField>

classes/ContactUtilitiesClassTest.cls
@isTest
private class ContactUtilitiesClassTest
{
	// Get the RecordTypeId
	public static ID eitcId = schema.SObjectType.Account.getRecordTypeInfosByName().get('EITC Site').getRecordTypeId();
	public static ID volOppEitcId = schema.SObjectType.HOC__Volunteer_Opportunity__c.getRecordTypeInfosByName().get('EITC Site').getRecordTypeId();

	@isTest
	static void testContactConnectionCalculation()
	{
		User emily = [SELECT Id FROM User WHERE CommunityNickname =: 'erackleff'][0];
		String emilyId = emily.Id;

		// Create an Organization
		Account acc = new Account();
		acc.Name = 'Test Nonprofit 1';
		acc.RecordTypeId = eitcId;
		acc.HOC__Status__c = 'Active Partner';
		acc.Walk_in_or_Appointment_Only__c = 'Walk-in';
		acc.HOC__Primary_Address__c = 'Shipping';
		acc.HOC__Address_Visibility__c = 'City and Zip only';
		acc.ShippingStreet = '123 Fake Street';
		acc.ShippingCity = 'Fake City';
		acc.ShippingState = 'MA';
		acc.ShippingPostalCode = '02446';
		acc.ShippingCountry = 'USA';
		acc.HOC__Partner_Approval_Manager__c = emilyId;
		acc.HOC__Impact_Area__c = 'Adult Education';
		insert acc;

		// Create a Volunteer
		Contact con = new Contact();
		con.HOC__Username__c = 'test@bostoncares.org';
		con.HOC__Registration_Status__c = 'Registered';
		con.FirstName = 'Test';
		con.LastName = 'User1';
		con.AccountId = acc.id;
		con.HOC__Primary_Phoneno__c = 'Home';
		con.Email = 'test@bostoncares.org';
		con.HOC__Primary_Address__c = 'Home';
		con.MailingStreet = '234 Fake Street';
		con.MailingCity = 'Boston';
		con.MailingState = 'MA';
		con.MailingPostalCode = '02446';
		con.MailingCountry = 'USA';
		con.Birthdate = System.Today().addYears(-25);
		con.HOC__Orientation_Completed__c = TRUE;
		con.VL_Training_Completed__c = TRUE;
		insert con;

		// Create a Zip Code
		HOC__ZipCode__c zipCodeRecord = new HOC__ZipCode__c();
		zipCodeRecord.Name = '02446';
		insert zipCodeRecord;

		// Create a Location
		HOC__Location__c locationRecord = new HOC__Location__c();
		locationRecord.Name = 'Test Location';
		locationRecord.HOC__Street__c = 'Test Street';
		locationRecord.HOC__City__c = 'Test City';
		locationRecord.HOC__Zip_Postal_Code__c = zipCodeRecord.id;
		locationRecord.HOC__Zip_Code__c = '02446';
		locationRecord.HOC__Country__c = 'USA';
		locationRecord.HOC__Organization__c = acc.id;
		insert locationRecord;

		// Create a Volunteer Opportunity
		HOC__Volunteer_Opportunity__c voloppRecord = new HOC__Volunteer_Opportunity__c();
		voloppRecord.Name = 'Test project';
		voloppRecord.HOC__Status__c = 'Pending';
		voloppRecord.HOC__Posting_Status__c = 'This is not published. Please submit for approval.';
		voloppRecord.RecordTypeId = volOppEitcId;
		voloppRecord.HOC__Type__c = 'Project';
		voloppRecord.HOC__Schedule_Type__c = 'Date & Time Specific';
		voloppRecord.HOC__Disaster_Opportunity_Type__c = 'Not Disaster Related';
		voloppRecord.HOC__Start_Date__c = System.Today().addDays(-30);
		voloppRecord.HOC__End_Date__c = System.Today().addDays(30);
		voloppRecord.HOC__Managed_By__c = 'Partner';
		voloppRecord.HOC__Organization_Served__c = acc.id;
		voloppRecord.HOC__Default_Location__c = locationRecord.id;
		voloppRecord.HOC__Registration_Type__c = 'Sign Up';
		voloppRecord.HOC__Apply_Restrictions_to_Opportunity__c = 'Apply Restrictions';
		voloppRecord.HOC__Registration_Deadline__c = 1;
		voloppRecord.HOC__Maximum_Attendance__c = 2;
		voloppRecord.HOC__Minimum_Attendance__c = 1;
		voloppRecord.HOC__Opportunity_Coordinator__c = con.id;
		voloppRecord.HOC__Minimum_Age_w_adult__c = 18;
		voloppRecord.HOC__Minimum_Age_w_o_adult__c = 18;
		voloppRecord.HOC__Orientation_Required__c = TRUE;
		voloppRecord.HOC__Skilled_Volunteer_Required__c = 'No';
		voloppRecord.HOC__Primary_Impact_Area__c = 'Adult Education';
		voloppRecord.HOC__Genders_Served__c = 'All Genders Served';
		voloppRecord.HOC__Impact_Area_Local__c = 'Boston Cares Programming & Support';
		voloppRecord.HOC__Program_Area_Local__c = 'Calendar';
		insert voloppRecord;

		// Create an Occurrence
		HOC__Occurrence__c occRecord = new HOC__Occurrence__c();
		occRecord.HOC__Volunteer_Opportunity__c = volOppRecord.id;
		occRecord.HOC__Location__c = locationRecord.id;
		occRecord.HOC__Start_Date_Time__c = System.Now().addDays(10);
		occRecord.HOC__End_Date_Time__c = System.Now().addDays(10).addHours(1);
		occRecord.HOC__Posting_Status__c = 'This is not published. The Volunteer Opportunity is not active.';
		occRecord.HOC__Status__c = 'Active';
		//occRecord.HOC__Days_Times_Needed__c = 'Tuesday Afternoon';
		occRecord.HOC__Opportunity_Coordinator__c = con.id;
		occRecord.HOC__Volunteer_Coordinator_Email__c = 'test@bostoncares.org';
		insert occRecord;

		// Create a Connection
		HOC__Connection__c connectionRecord = new HOC__Connection__c();
		connectionRecord.HOC__Volunteer_Opportunity__c = voloppRecord.id;
		connectionRecord.HOC__Occurrence__c = occRecord.id;
		connectionRecord.HOC__Contact__c = con.id;
		connectionRecord.HOC__Role__c = 'Volunteer';
		connectionRecord.HOC__Status__c = 'Confirmed';
		connectionRecord.HOC__Attendance_Status__c = 'Attended (and Hours Verified)';
		insert connectionRecord;

		List<Contact> listOfCons = new List<Contact>([SELECT Id, Number_of_Projects_Attended_and_Verified__c, (SELECT Id FROM HOC__Connection__r WHERE HOC__Attendance_Status__c =: 'Attended (and Hours Verified)') FROM Contact WHERE ID IN (SELECT HOC__Contact__c FROM HOC__Connection__c)]);
		ContactUtilitiesClass.calculateConnections();
		ContactUtilitiesClass.batchCalculateConnections(listOfCons);
	}
}