force-app/main/default/objects/HOC__Volunteer_Opportunity__c/HOC__Volunteer_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Opportunity_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>HOC__Opportunity_Coordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Coordinator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a valid contact.</errorMessage>
        <filterItems>
            <field>Contact.HOC__Username__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <infoMessage>You can only assign contacts with the username field populated as Opportunity Coordinators.
If you do not see the contact you need in the search results, please contact the staff at the volunteer center to verify the contact record.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Opportunities</relationshipLabel>
    <relationshipName>Volunteer_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Status__c.field-meta.xml
<CustomField>
    <fullName>HOC__Status__c</fullName>
    <inlineHelpText>Active - visible on website 
Pending - not yet visible publicly 
Awaiting Approval - submitted for approval by partner 
Admin - opportunities managed internally, not for public view 
Inactive – formally active, now retired from use on public site</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#E27001</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <color>#78C953</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <color>#0B6FCE</color>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#A845DC</color>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Volunteer_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>HOC__Volunteer_Coordinator_Email__c</fullName>
    <label>Opportunity Coordinator Email</label>
    <type>Email</type>
</CustomField>

src/objects/OrphanedProject__c.object
<CustomObject>
    <label>Orphaned Project</label>
    <nameField>
        <label>Orphaned Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphaned Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Occurrence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Occurrence</label>
        <referenceTo>HOC__Occurrence__c</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VolunteerLeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to keep track of the volunteer leader that is claiming an orphaned project.</description>
        <label>Volunteer Leader</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VolunteerOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the parent Volunteer Opportunity record.</description>
        <label>Volunteer Opportunity</label>
        <referenceTo>HOC__Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/OrphanedProject__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is used to keep track of the Status of a given VL Need record.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VL Needed</fullName>
            </value>
            <value>
                <fullName>Pending BC Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrphanedProject__c/recordTypes/OrphanedOccurrence.recordType-meta.xml
<RecordType>
    <fullName>OrphanedOccurrence</fullName>
    <active>true</active>
    <label>Orphaned Occurrence</label>
</RecordType>

force-app/main/default/objects/OrphanedProject__c/recordTypes/OrphanedOpportunity.recordType-meta.xml
<RecordType>
    <fullName>OrphanedOpportunity</fullName>
    <active>true</active>
    <label>Orphaned Opportunity</label>
</RecordType>

force-app/main/default/classes/OrphanedProjectTriggerHandler.cls
public class OrphanedProjectTriggerHandler extends TriggerHandler {
    private static final Map<Id, Schema.RecordTypeInfo> RT_BY_ID = Schema.SObjectType.OrphanedProject__c.getRecordTypeInfosById();
    public override void afterUpdate() {
        approvePendingVLNeeds((List<OrphanedProject__c>) Trigger.New, (Map<Id, OrphanedProject__c>) Trigger.oldMap);
    }

    private void approvePendingVLNeeds(List<OrphanedProject__c> newVLNeeds, Map<Id, OrphanedProject__c> oldMap) {
        Map<Id, OrphanedProject__c> oppsToReassign = new Map<Id, OrphanedProject__c>();
        Map<Id, OrphanedProject__c> occurrencesToReassign = new Map<Id, OrphanedProject__c>();
        Set<Id> volunteerLeaderIds = new Set<Id>();
        List<SObject> objectsToUpdate = new List<SObject>();

        for(OrphanedProject__c vlneed : newVLNeeds) {
            if(vlneed.Status__c != oldMap.get(vlneed.Id).Status__c &&
               vlneed.Status__c == 'Approved'){
                String recTypeName = RT_BY_ID.get(vlneed.RecordTypeId).getDeveloperName();
                if(recTypeName == 'OrphanedOpportunity') {
                    oppsToReassign.put(vlneed.VolunteerOpportunity__c, vlneed);
                } else if(recTypeName == 'OrphanedOccurrence') {
                    occurrencesToReassign.put(vlneed.Occurrence__c, vlneed);
                }
            }
        }

        Map<Id, Contact> volunteerLeaders = new Map<Id, Contact>([SELECT Id, Email FROM Contact WHERE Id IN: volunteerLeaderIds]);

        for(Id oppId: oppsToReassign.keySet()) {
            HOC__Volunteer_Opportunity__c opp = new HOC__Volunteer_Opportunity__c(
                                                    Id = oppId,
                                                    HOC__Opportunity_Coordinator__c = oppsToReassign.get(oppId).VolunteerLeader__c,
                                                    HOC__Volunteer_Coordinator_Email__c = volunteerLeaders.get(oppsToReassign.get(oppId).VolunteerLeader__c).Email
                                                );
            objectsToUpdate.add(opp);
            //TODO: determine whether new Occurrences would need to be automatically created or not.
        }

        for(Id occId: occurrencesToReassign.keySet()){
            HOC__Occurrence__c occ = new HOC__Occurrence__c(
                                        Id = occId,
                                        HOC__Opportunity_Coordinator__c = occurrencesToReassign.get(occId).VolunteerLeader__c,
                                        HOC__Volunteer_Coordinator_Email__c = volunteerLeaders.get(occurrencesToReassign.get(occId).VolunteerLeader__c).Email
                                     );
            objectsToUpdate.add(occ);
        }

        for(HOC__Connection__c c: [SELECT Id, HOC__Contact__c, HOC__Volunteer_Opportunity__c, HOC__Occurrence__c
                                   FROM HOC__Connection__c
                                   WHERE 
                                   (HOC__Occurrence__c IN: occurrencesToReassign.keySet() OR
                                   HOC__Volunteer_Opportunity__c IN: oppsToReassign.keySet()) AND
                                   HOC__Role__c = 'Volunteer Leader' AND
                                   HOC__Status__c = 'Confirmed' AND
                                   HOC__Attendance_Status__c = 'Please Verify']){
            // Bulk decline any Connections tied to the parent Volunteer Opportunity that is being approved for the new VL
            if(oppsToReassign.containsKey(c.HOC__Volunteer_Opportunity__c) &&
               c.HOC__Contact__c != oppsToReassign.get(c.HOC__Volunteer_Opportunity__c).VolunteerLeader__c) {
                c.HOC__Status__c = 'Declined';
                c.HOC__Attendance_Status__c = 'Declined';
                objectsToUpdate.add(c);
            // Bulk decline any Connections tied to the parent Occurrence that is being approved for the new VL
            } else if(occurrencesToReassign.containsKey(c.HOC__Occurrence__c) &&
                      c.HOC__Contact__c != occurrencesToReassign.get(c.HOC__Occurrence__c).VolunteerLeader__c){ 
                c.HOC__Status__c = 'Declined';
                c.HOC__Attendance_Status__c = 'Declined';
                objectsToUpdate.add(c);
            }
        }

        update objectsToUpdate;
    }
}