force-app/main/default/objects/HOC__Volunteer_Opportunity__c/HOC__Volunteer_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HOC__Volunteer_Opportunity__c/fields/HOC__Organization_Served_Name__c.field-meta.xml
<CustomField>
    <fullName>HOC__Organization_Served_Name__c</fullName>
    <formula>HOC__Organization_Served__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is populated automatically from your selection in the &quot;Organization Served&quot; field.  The field is used when populating text in e-mail notices, etc.</inlineHelpText>
    <label>Organization Served Name</label>
    <type>Text</type>
</CustomField>

src/objects/OrphanedProject__c.object
<CustomObject>
    <label>Orphaned Project</label>
    <nameField>
        <label>Orphaned Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphaned Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>HOC__Location__c</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Occurrence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Occurrence</label>
        <referenceTo>HOC__Occurrence__c</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VolunteerLeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to keep track of the volunteer leader that is claiming an orphaned project.</description>
        <label>Volunteer Leader</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VolunteerOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the parent Volunteer Opportunity record.</description>
        <label>Volunteer Opportunity</label>
        <referenceTo>HOC__Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/OrphanedProject__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <formula>IF(ISBLANK(Occurrence__c),  
TEXT(MONTH(VolunteerOpportunity__r.HOC__End_Date__c))+&quot;/&quot; +TEXT(DAY(VolunteerOpportunity__r.HOC__End_Date__c))+&quot;/&quot; +TEXT(YEAR(VolunteerOpportunity__r.HOC__End_Date__c)),
TEXT(MONTH(DATEVALUE(Occurrence__r.HOC__End_Date_Time__c )))+&quot;/&quot; +TEXT(DAY(DATEVALUE(Occurrence__r.HOC__End_Date_Time__c )))+&quot;/&quot; +TEXT(YEAR(DATEVALUE(Occurrence__r.HOC__End_Date_Time__c ))) + &quot; &quot; + TEXT(VALUE(MID(TEXT(TIMEVALUE(Occurrence__r.HOC__End_Date_Time__c )), 0,2)) -  $CustomMetadata.BostonCaresSetting__mdt.DefaultBostonCaresSettings.TimezoneOffset__c) + MID(TEXT(TIMEVALUE(Occurrence__r.HOC__End_Date_Time__c )), 3,3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date/Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrphanedProject__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>IF( ISBLANK(Occurrence__c), &quot;Volunteer Opportunity&quot;, &quot;Occurrence&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrphanedProject__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <formula>IF(ISBLANK(Occurrence__c),
TEXT(MONTH(VolunteerOpportunity__r.HOC__Start_Date__c))+&quot;/&quot; +TEXT(DAY(VolunteerOpportunity__r.HOC__Start_Date__c))+&quot;/&quot; +TEXT(YEAR(VolunteerOpportunity__r.HOC__Start_Date__c)),
TEXT(MONTH(DATEVALUE(Occurrence__r.HOC__Start_Date_Time__c)))+&quot;/&quot; +TEXT(DAY(DATEVALUE(Occurrence__r.HOC__Start_Date_Time__c)))+&quot;/&quot; +TEXT(YEAR(DATEVALUE(Occurrence__r.HOC__Start_Date_Time__c))) + &quot; &quot; + TEXT(VALUE(MID(TEXT(TIMEVALUE(Occurrence__r.HOC__Start_Date_Time__c)), 0,2)) - $CustomMetadata.BostonCaresSetting__mdt.DefaultBostonCaresSettings.TimezoneOffset__c) + MID(TEXT(TIMEVALUE(Occurrence__r.HOC__Start_Date_Time__c)), 3,3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date/Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrphanedProjectController.cls
global class OrphanedProjectController {
    /*
     * This custom object should be used, when/if OWD for HOC__Volunteer_Opportunity__c
     * has to remain Private. 
     * Assumptions: 
     * 1. Given an OrphanedProject__c record, there are 2 possibilities: 
     *    (1) VolunteerOpportunity__c is populated, while Occurrence__c is not. This is used
     *        to track projects that should/could be claimed as a whole. 
     *    (2) Both VolunteerOpportunity__c and Occurrence__c are populated. This is used to 
     *        track orphaned project occurrences that should/could be claimed individually. 
     * 2. Consider building flags and trigger logic to quickly enable BostonCares staff
     *    to quickly generate an Orphaned Project record on the volunteer opportunity level, 
     *    or to quickly generate an Orphaned Project record for each Ocurrence records under a 
     *    given volunteer opportunity.
     * 3. Here are the assumptions around which Salesforce field(s) correspond to the
     *    excel columns:
     *    (1) Orgnization Served = VolunteerOpportunity__r.HOC__Organization_Served_Name__c
     *    (2) Activity = VolunteerOpportunity__r.Name
     *    (3) Location = Location__c
          (4) Monthly Days = ?
          (5) Time = ?
          (6) Volunteer Leader = VolunteerLeader__r.Name
          (7) Alternate Volunteer Leader = ?
          (8) Partner Staff as VL = ?

    * 4. Going forward, in order for BC to open up an Occurrence for VL to claim, BC would need to 
         create an Occurrence record first, and then use the NewVolunteerLeaderNeeds flow to generate VL Needs.
         This is a change compared to how the Google Sheet works. 
    * 5. Given a Volunteer Opportunity, BC would decide to either share the entire Volunteer Opportunity for VLs to grab,
         or share the occurrences for VLs to grab, but it would never be both.
    */
    @AuraEnabled(cacheable=false)
    global static List<OrphanedProject__c> getOrphanedProjects() {
        return [SELECT Id, VolunteerOpportunity__r.Name,
                VolunteerLeader__c, VolunteerLeader__r.Name,
                Level__c, StartDateTime__c, EndDateTime__c,
                Location__c
                FROM OrphanedProject__c];
    }
}