force-app/main/default/objects/HOC__Volunteer_Opportunity__c/HOC__Volunteer_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Opportunity</label>
    <nameField>
        <label>Volunteer Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrphanedProject__c.object
<CustomObject>
    <label>Orphaned Project</label>
    <nameField>
        <label>Orphaned Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orphaned Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>HOC__Location__c</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VolunteerLeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to keep track of the volunteer leader that is claiming an orphaned project.</description>
        <label>Volunteer Leader</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VolunteerOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the parent Volunteer Opportunity record.</description>
        <label>Volunteer Opportunity</label>
        <referenceTo>HOC__Volunteer_Opportunity__c</referenceTo>
        <relationshipLabel>Orphaned Projects</relationshipLabel>
        <relationshipName>OrphanedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/OrphanedProject__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <formula>IF(ISBLANK(Occurrence__c),  
TEXT(MONTH(VolunteerOpportunity__r.HOC__End_Date__c))+&quot;/&quot; +TEXT(DAY(VolunteerOpportunity__r.HOC__End_Date__c))+&quot;/&quot; +TEXT(YEAR(VolunteerOpportunity__r.HOC__End_Date__c)),
TEXT(MONTH(DATEVALUE(Occurrence__r.HOC__End_Date_Time__c )))+&quot;/&quot; +TEXT(DAY(DATEVALUE(Occurrence__r.HOC__End_Date_Time__c )))+&quot;/&quot; +TEXT(YEAR(DATEVALUE(Occurrence__r.HOC__End_Date_Time__c ))) + &quot; &quot; + TEXT(VALUE(MID(TEXT(TIMEVALUE(Occurrence__r.HOC__End_Date_Time__c )), 0,2)) -  $CustomMetadata.BostonCaresSetting__mdt.DefaultBostonCaresSettings.TimezoneOffset__c) + MID(TEXT(TIMEVALUE(Occurrence__r.HOC__End_Date_Time__c )), 3,3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date/Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrphanedProject__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>IF( ISBLANK(Occurrence__c), &quot;Volunteer Opportunity&quot;, &quot;Occurrence&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrphanedProject__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <formula>IF(ISBLANK(Occurrence__c),
TEXT(MONTH(VolunteerOpportunity__r.HOC__Start_Date__c))+&quot;/&quot; +TEXT(DAY(VolunteerOpportunity__r.HOC__Start_Date__c))+&quot;/&quot; +TEXT(YEAR(VolunteerOpportunity__r.HOC__Start_Date__c)),
TEXT(MONTH(DATEVALUE(Occurrence__r.HOC__Start_Date_Time__c)))+&quot;/&quot; +TEXT(DAY(DATEVALUE(Occurrence__r.HOC__Start_Date_Time__c)))+&quot;/&quot; +TEXT(YEAR(DATEVALUE(Occurrence__r.HOC__Start_Date_Time__c))) + &quot; &quot; + TEXT(VALUE(MID(TEXT(TIMEVALUE(Occurrence__r.HOC__Start_Date_Time__c)), 0,2)) - $CustomMetadata.BostonCaresSetting__mdt.DefaultBostonCaresSettings.TimezoneOffset__c) + MID(TEXT(TIMEVALUE(Occurrence__r.HOC__Start_Date_Time__c)), 3,3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date/Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrphanedProjectControllerTest.cls
/**
 * Test class providing functional validation and code coverage for
 * the OrphanedProjectController class.
 */
@isTest(isParallel=false)
private class OrphanedProjectControllerTest {
    private static final Map<String, Schema.RecordTypeInfo> RT_BY_NAME = Schema.SObjectType.OrphanedProject__c.getRecordTypeInfosByName();

    /**
     * Create all test data required for this test class.
     */
    @testSetup
    private static void setup() {
        User u = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND UserRoleId != NULL AND IsActive = TRUE LIMIT 1];
        Account a = TestDataFactory.newAccount(u);
        insert a; 
        
        List<Contact> contacts = TestDataFactory.newContacts(2, a.Id);
        insert contacts;

        // You cannot simply insert a Contact with this value populated
		// HOC trigger only kicks in properly if you update the Contact
        for(Contact c: contacts){
            c.HOC__Contact_Login_Profile__c = 'Volunteer Leader';
        }
        update contacts;

        HOC__ZipCode__c zipCodeRec = new HOC__ZipCode__c(Name = '02116');
        insert zipCodeRec;

        HOC__Location__c locationRec = TestDataFactory.newLocationRec(zipCodeRec.Id, a.Id);
        insert locationRec;

        // Create a Volunteer Opportunity w/o any child records
        HOC__Volunteer_Opportunity__c volOppStandAlone = TestDataFactory.newVolOppRec(a.Id, locationRec.Id, contacts[0].Id);
        insert volOppStandAlone;

        // inserting a VL Need record for the standalone Volunteer Opportunity
        OrphanedProject__c volOppVlNeed = TestDataFactory.newVLNeed(volOppStandAlone.Id, null, contacts[1].Id, 'Pending BC Approval');
        insert volOppVlNeed;
    }


    /* 
     * Ensure that the retrieval SOQL is functioning as expected.
    */ 
    @isTest
	private static void testGetOrphanedProjects() {
        List<OrphanedProject__c> vlneeds = [SELECT Id, VolunteerOpportunity__r.Name,
                                            VolunteerLeader__c, VolunteerLeader__r.Name,
                                            Level__c, StartDateTime__c, EndDateTime__c,
                                            Location__c
                                            FROM OrphanedProject__c];

        List<OrphanedProject__c> retrieved = OrphanedProjectController.getOrphanedProjects();
        
        system.assertEquals(vlneeds.size(), retrieved.size());
    }
}